DROP TABLE IF EXISTS Laakari CASCADE;
DROP TABLE IF EXISTS Potilas CASCADE;
DROP TABLE IF EXISTS Historia CASCADE;
DROP TABLE IF EXISTS Kaynti CASCADE;
DROP TABLE IF EXISTS Raportti CASCADE;
DROP TABLE IF EXISTS Ohje CASCADE;